config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/', to: 'games#index'
  resources :games, only: %i[index show] do
    resources :scores, only: :create
  end
  get '/score/:id', to: 'scores#update', as: 'score'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :scores
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validates :points, :game, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :scores

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :find_device_type
  before_action :store_user_location!, if: :storable_location?
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  private

  def find_device_type
    user_agent = request.user_agent
    client = DeviceDetector.new(user_agent)
    @device = client.device_type

    # @device = 'smartphone'
  end

  def store_user_location!
    store_location_for(:user, request.fullpath)
  end

  def storable_location?
    is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end

  def after_sign_out_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  skip_before_action :authenticate_user!, only: :create

  def create
    respond_to do |format|
      format.json do
        @score = Score.new(score_params)
        @game = Game.find(params[:game_id])
        @score.game = @game
        if user_signed_in?
          @score.user = current_user
        else
          @score.user_id = 0
        end
        @score.save
        game_over = render_to_string(
          partial: "games/#{@game.name.downcase}/game_over",
          formats: :html,
          locals: { score: @score, game: @game }
        )

        high_scores = render_to_string(
          partial: "games/#{@game.name.downcase}/high_scores",
          formats: :html,
          locals: { scores: @game.scores }
        )
        render json: { highscores: high_scores, gameOver: game_over }
      end
    end
  end

  def update
    @score = Score.find(params[:id])

    if @score.user_id == 0
      @score.update(user: current_user)
    end
    @game = @score.game
    redirect_to game_path(@game)
  end

  private

  def score_params
    if params[:key] == Digest::SHA256.hexdigest(params[:score][:points].to_s)
      params.require(:score).permit(:points)
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/score_helper.rb
module ScoreHelper
end

app/views/games/_tetris.html.erb
<div class="tetris" data-controller="tetris" data-action="keydown@window->tetris#moveInput keyup@window->tetris#removeInput" data-tetris-link-value="<%= game_scores_path(game) %>">
  <h2 class="text-center" data-tetris-target="level">Level 1</h2>
  <div class="row justify-content-center w-100">
    <div class="col-3">
      <div id="high-scores" class="high-scores scoreboard" data-tetris-target="highscores">
        <%= render 'games/high_scores.html.erb', scores: game.scores %>
      </div>
    </div>
    <div class="col-6 d-flex flex-column align-items-center">
      <div class="board">
        <% y = 0 %>
        <% 22.times do %>
          <div class="d-flex justify-content-center" data-tetris-target="row">
            <% x = 0 %>
            <% 12.times do %>
              <div id="<%= x %>,<%= y %>" class="grid empty" data-tetris-target="grid"></div>
              <% x += 1 %>
            <% end %>
          </div>
          <% y += 1 %>
        <% end %>
      <%= render 'games/start_game.html.erb' %>
      <div data-tetris-target="gameOver"></div>
      <div data-tetris-target="paused"></div>
      </div>
      <div class="volume-control d-flex justify-content-end w-50 pt-1">
        <p>
          <i class="fa-solid fa-volume-high"  data-action="click->tetris#mute" data-tetris-target="muteBtn"></i>
          <i class="fa-solid fa-volume-xmark" data-action="click->tetris#unmute" data-tetris-target="unmuteBtn"></i>
        </p>
      </div>
    </div>


    <div id="score" class="col-3">
      <div class="scoreboard">
        <h3 class="text-end pe-3">Score</h3>
        <h3 data-tetris-target="score" class="text-end pe-3 pb-3">0</h3>
      </div>
      <div class="next-piece mt-3">
        <% y = -1 %>
        <% 5.times do %>
          <div class="d-flex justify-content-center">
            <% x = 4 %>
            <% 5.times do %>
              <div id="next-<%= x %>,<%= y %>" class="next-grid empty" data-tetris-target="nextGrid"></div>
              <% x += 1 %>
            <% end %>
          </div>
          <% y += 1 %>
        <% end %>
      </div>
    </div>
  </div>


  <audio data-tetris-target="music" src="<%= audio_path 'tetris.weba'%>" type="audio/weba" loop></audio>
  <audio data-tetris-target="loseAudio" src="<%= audio_path 'lose.m4a'%>" type="audio/m4a"></audio>
  <audio data-tetris-target="pauseAudio" src="<%= audio_path 'pause.weba'%>" type="audio/weba"></audio>
  <audio data-tetris-target="lineClearAudio" src="<%= audio_path 'lineclear.weba'%>" type="audio/weba"></audio>
</div>

app/views/games/index.html.erb
<h1 class="pt-5">Select a game</h1>


<div id="game-list" class="d-flex flex-column align-items-center justify-content-center pt-5">
  <% @games.each do |game| %>
    <%= link_to game.name.upcase, game_path(game) %>
  <% end %>
</div>

app/views/games/show.html.erb
<% if @device == 'smartphone' || @device == 'tablet' %>
  <%= render "games/#{@game.name.downcase}/mobile/#{@game.name.downcase}", formats: :html, game: @game %>
<% else %>
  <%= render "games/#{@game.name.downcase}/#{@game.name.downcase}", formats: :html, game: @game %>
<% end %>

app/views/games/tetris/_game_over.html.erb
<div id="game-over">
  <% if game.scores.order(points: 'desc').first(10).include?(score) && score.points > 0 %>
    <h2 class="mb-5">NEW HIGHSCORE!</h2>
  <% else %>
    <H2>GAME OVER</H2>
  <% end %>

  <button class="m-3" data-tetris-target="replayBtn" data-action="click->tetris#replay">PLAY AGAIN?</button>

  <% unless user_signed_in? %>
    <div class="my-5 d-flex flex-column align-items-center justify-content-center">
      <h3>Sign in to save your score.</h3>
      <%= link_to 'Sign in', score_path(score) %>
    </div>
  <% end %>
</div>

app/views/games/tetris/_high_scores.html.erb
<h3 class="pt-1">Highscores</h3>

<div class="d-flex flex-column pt-3">
  <% if scores.order(points: :desc).where('points > 0').count > 0 %>
    <% scores.order(points: :desc).where('points > 0').first(10).each do |score| %>
      <div class="d-flex justify-content-between">
        <p><%= score.user.username %></p>
        <p><%= score.points %></p>
      </div>
    <% end %>
  <% else %>
    <p>No highscores yet.</p>
  <% end %>
</div>

app/views/games/tetris/_start_game.html.erb
<div id="start" data-tetris-target="start">
  <h2>Controls</h2>

  <div class="d-flex justify-content-between w-100 px-3">
    <p class="action">Move</p>
    <div class="d-flex justify-content-between">
      <p class="ps-1"><i class="fa-solid fa-arrow-left-long"></i></p>
      <p class="ps-1"><i class="fa-solid fa-arrow-down-long"></i></p>
      <p class="ps-1"><i class="fa-solid fa-arrow-right-long"></i></p>
    </div>
  </div>

  <div class="d-flex justify-content-between w-100 text-end px-3">
    <p>Rotate</p>
    <p>SPACE</p>
  </div>

  <div class="d-flex justify-content-between w-100 text-end px-3">
    <p>Mute</p>
    <p>M</p>
  </div>

  <div class="d-flex justify-content-between w-100 text-end px-3">
    <p>Pause</p>
    <p>P</p>
  </div>
  <button data-action="click->tetris#start" data-tetris-target="startBtn">START</button>
</div>

app/views/games/tetris/_tetris.html.erb
<div class="tetris pt-3" data-controller="tetris" data-action="keydown@window->tetris#moveInput keyup@window->tetris#otherInput resize@window->tetris#drawGrids" data-tetris-link-value="<%= game_scores_path(game) %>">
  <div class="row justify-content-center w-100">
    <div class="d-none d-md-block col-4 col-lg-3">
      <div id="high-scores" class="high-scores scoreboard" data-tetris-target="highscores">
        <%= render 'games/tetris/high_scores', formats: :html, scores: game.scores %>
      </div>
    </div>

    <div id="game" class="col-6 col-md-4 d-flex flex-column align-items-center" data-tetris-target="mainGridRow">
      <h2 class="text-center" data-tetris-target="level">Level 1</h2>
      <div class="board" data-action="touchmove->tetris#touchControl touchstart->tetris#setTouchCoordinates touchend->tetris#touchRotate">
        <% y = 0 %>
        <% 22.times do %>
          <div class="d-flex justify-content-center" data-tetris-target="row">
            <% x = 0 %>
            <% 12.times do %>
              <div id="<%= x %>,<%= y %>" class="grid empty" data-tetris-target="grid"></div>
              <% x += 1 %>
            <% end %>
          </div>
          <% y += 1 %>
        <% end %>
      <%= render 'games/tetris/start_game', formats: :html %>
      <div data-tetris-target="gameOver"></div>
      <div data-tetris-target="paused"></div>
      </div>
      <div class="volume-control d-flex justify-content-end w-50 pt-1">
        <p class="pe-3">
          <i class="fa-solid fa-pause" data-action="click->tetris#pauseGame" data-tetris-target="pauseBtn"></i>
          <i class="fa-solid fa-play" data-action="click->tetris#pauseGame" data-tetris-target="unpauseBtn"></i>
        </p>
        <p>
          <i class="fa-solid fa-volume-high"  data-action="click->tetris#mute" data-tetris-target="muteBtn"></i>
          <i class="fa-solid fa-volume-xmark" data-action="click->tetris#unmute" data-tetris-target="unmuteBtn"></i>
        </p>
      </div>
    </div>


    <div id="score" class="col-4 col-lg-3 col-xl-2 d-flex flex-column align-items-end">
      <div class="scoreboard w-100">
        <h3 class="text-end pt-1 px-3 m-0">Score</h3>
        <p data-tetris-target="score" class="text-end pe-3 py-3 m-0">0</p>
      </div>
      <div class="next-piece py-3 mt-3 w-100" data-tetris-target="nextGridRow">
        <% y = 0 %>
        <% 4.times do %>
          <div class="d-flex justify-content-center">
            <% x = 0 %>
            <% 3.times do %>
              <div id="next-<%= x %>,<%= y %>" class="next-grid empty" data-tetris-target="nextGrid"></div>
              <% x += 1 %>
            <% end %>
          </div>
          <% y += 1 %>
        <% end %>
      </div>
    </div>
  </div>


  <%= audio_tag 'tetris.weba', 'tetris.m4a', data: {tetris_target: :music}, loop: true %>
  <%= audio_tag 'lose.m4a', data: {tetris_target: :loseAudio}%>
  <%= audio_tag 'pause.weba', 'pause.m4a', data: {tetris_target: :pauseAudio} %>
  <%= audio_tag 'lineclear.weba', 'lineclear.m4a', data: {tetris_target: :lineClearAudio}%>
</div>

app/views/games/tetris/mobile/_start_game.html.erb
<div id="start" data-tetris-target="start">
  <h2>Controls</h2>

  <div class="d-flex justify-content-between w-100 px-3">
    <p class=" action">Move</p>
    <div class="d-flex justify-content-between">
      <p class="ps-3">SCROLL</p>
    </div>
  </div>

  <div class="d-flex justify-content-between w-100 text-end px-3">
    <p class="">Rotate</p>
    <p class="">TAP</p>
  </div>

  <button data-action="click->tetris#start" data-tetris-target="startBtn">START</button>
</div>

app/views/games/tetris/mobile/_tetris.html.erb
<div class="tetris pt-3" data-controller="tetris" data-action="keydown@window->tetris#moveInput keyup@window->tetris#otherInput resize@window->tetris#drawGrids" data-tetris-link-value="<%= game_scores_path(game) %>">
  <!-- Modal -->
  <div id="highscores-modal">
    <button class="close"><span>&times;</span></button>
    <div class="content" data-tetris-target="highscores">
      <%= render 'games/tetris/high_scores', formats: :html, scores: game.scores %>
    </div>
  </div>

  <div class="row justify-content-center w-100">
    <div class="row justify-content-center">
      <div id="score" class="col-12 col-sm-8 col-md-6">
        <div class="scoreboard d-flex justify-content-between">
          <h3 class="text-end ps-3 py-1 m-0">Score</h3>
          <p data-tetris-target="score" class="text-end pe-3 py-1 m-0">0</p>
        </div>
      </div>
    </div>
    <div class="row mt-3 justify-content-between">
      <div class="col-8 col-md-6">
        <div id="high-scores" class="high-scores scoreboard">
          <h3 class="text-center py-1 m-0" data-action="click->tetris#showHighscores">Show highscores</h3>
        </div>
      </div>
      <div class="next-piece col-3 py-3" data-tetris-target="nextGridRow">
        <% y = 0 %>
        <% 4.times do %>
          <div class="d-flex justify-content-center">
            <% x = 0 %>
            <% 3.times do %>
              <div id="next-<%= x %>,<%= y %>" class="next-grid empty" data-tetris-target="nextGrid"></div>
              <% x += 1 %>
            <% end %>
          </div>
          <% y += 1 %>
        <% end %>
      </div>
    </div>

    <div class="col-12 d-flex flex-column align-items-center pt-3" data-tetris-target="mainGridRow">
      <h2 class="text-center" data-tetris-target="level">Level 1</h2>
      <div class="board" data-action="touchmove->tetris#touchControl touchstart->tetris#setTouchCoordinates touchend->tetris#touchRotate">
        <% y = 0 %>
        <% 22.times do %>
          <div class="d-flex justify-content-center" data-tetris-target="row">
            <% x = 0 %>
            <% 12.times do %>
              <div id="<%= x %>,<%= y %>" class="grid empty" data-tetris-target="grid"></div>
              <% x += 1 %>
            <% end %>
          </div>
          <% y += 1 %>
        <% end %>

        <%= render 'games/tetris/mobile/start_game', formats: :html %>
        <div data-tetris-target="gameOver"></div>
        <div data-tetris-target="paused"></div>
      </div>

      <div class="volume-control d-flex justify-content-around w-100 pt-3">
        <p>
          <i class="fa-solid fa-pause" data-action="click->tetris#pauseGame" data-tetris-target="pauseBtn"></i>
          <i class="fa-solid fa-play" data-action="click->tetris#pauseGame" data-tetris-target="unpauseBtn"></i>
        </p>

        <p>
          <i class="fa-solid fa-volume-high"  data-action="click->tetris#mute" data-tetris-target="muteBtn"></i>
          <i class="fa-solid fa-volume-xmark" data-action="click->tetris#unmute" data-tetris-target="unmuteBtn"></i>
        </p>
      </div>
    </div>
  </div>

  <%= audio_tag 'tetris.weba', 'tetris.m4a', data: {tetris_target: :music}, loop: true %>
  <%= audio_tag 'lose.m4a', data: {tetris_target: :loseAudio}%>
  <%= audio_tag 'pause.weba', 'pause.m4a', data: {tetris_target: :pauseAudio} %>
  <%= audio_tag 'lineclear.weba', 'lineclear.m4a', data: {tetris_target: :lineClearAudio}%>
</div>

app/views/layouts/_navbar.html.erb
<div id="navbar" class="w-100">
  <div class="container d-flex justify-content-between py-2">
    <%= link_to 'Home', games_path %>

    <% if user_signed_in? %>
      <div class="py-2">
        <%= link_to 'My profile', edit_user_registration_path %>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
      </div>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @game ? @game.name.capitalize : "CSS games" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/8dbd947086.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar.html.erb' %>

    <div class="container">
      <%= yield %>
    </div>

    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% elsif alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
  </body>
</html>

app/views/score/create.html.erb
<h1>Score#create</h1>
<p>Find me in app/views/score/create.html.erb</p>